apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "tiny.db.elephantsql.com"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: "odkmrwsu"
            - name: KONG_PG_PASSWORD
              value: "o_XW5JCwM-Y7IG0tAis9gSfnaXSacUij"
            - name: KONG_PG_DATABASE
              value: "odkmrwsu"
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444